CREATE TABLE IF NOT EXISTS points (
    id SERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    r DOUBLE PRECISION NOT NULL,
    success BOOLEAN NOT NULL
);
